apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-naughtywriter
  labels:
    app: gbv-naughtywriter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbv-naughtywriter
  template:
    metadata:
      labels:
        app: gbv-naughtywriter
    spec:
      # restartPolicy: Always
      containers:
      - name: gbv-naughtywriter
        image: localhost:32000/naughtybot:registry
        imagePullPolicy: Always
        command: ['npm']
        args: ['run', 'naughtywriter']
        resources:
          requests:
            cpu: "10m"
            memory: "20Mi"
        env:
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "chatroach-cockroachdb-public.default"
        - name: CHATBASE_PORT
          value: "26257"
        - name: BOTSPINE_KAFKA_BROKERS
          value: "spinaltap-kafka:9092"
        - name: BOTSPINE_MESSAGE_TOPIC
          value: "chat-events"
