apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "naughtybot.fullname" . }}-writer
  labels:
    {{- include "naughtybot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.writer.replicaCount }}
  selector:
    matchLabels:
      {{- include "naughtybot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "naughtybot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: naughtywriter
          command: ['npm']
          args: ['run', 'naughtywriter']
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          resources:
            {{- toYaml .Values.writer.resources | nindent 12 }}
      {{- with .Values.writer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.writer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.writer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
